# Generated by Django 4.1.6 on 2023-07-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_issues'),
    ]

    operations = [
        migrations.AddField(
            model_name='herbs',
            name='description',
            field=models.TextField(default='...', max_length=1000),
        ),
        migrations.AddField(
            model_name='herbs',
            name='image',
            field=models.ImageField(default='image', upload_to='images/'),
            preserve_default=False,
        ),
    ]
